### ISSUE TITLE
Problem in first running

### ISSUE THREAD

**Issue by Dieggarp** [stevemussmann/BA3-SNPS-autotune#4]
Hi Steve,
I just arrived at BA3 and found your version for SNPs and your autotune. After changing the directory for python3 I tried to  run 
`./BA3-SNPS-autotune.py -h` 
and found the next error:
```
Traceback (most recent call last):
  File "./BA3-SNPS-autotune.py", line 4, in <module>
    from comline import ComLine
ModuleNotFoundError: No module named 'comline'
```

Could you please help me?

Thanks in advance
Diego

**Comment by stevemussmann** [comment]
Hi Diego,

Did you download the entire package? And if so, is the comline.py file present in the same directory as BA3-SNPS-autotune.py? The only thing I can think that would cause this problem is if the comline.py file is absent.

-Steve

**Comment by stevemussmann** [comment]
I'm going to take the "thumbs up" as a sign that this fixed the problem. If it did not, feel free to re-open this issue, or open a new one if you run into additional problems.

**Comment by Dieggarp** [comment]
Hi Steve,

Sorry that I didn´t reply, when realizing the cause of the problem and find
the program worked, I forgot totally to tell you.

But thanks! I was trying to run the .py outside the fold with the rest of
the necessary files.
Thanks again!!

Diego
